server {
  listen 80;
  server_name www.scan2dine.store scan2dine.store;

  return 301 https://scan2dine.store$request_uri;
}

server {
  listen 443 ssl;
  server_name www.scan2dine.store scan2dine.store;

  ssl_certificate     /etc/letsencrypt/live/scan2dine.store/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/scan2dine.store/privkey.pem;

  # fontend
  location / {
    proxy_pass http://frontend:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # backend api
  location /api/ {
    proxy_pass http://backend:8041;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # backend admin
  location /admin/ {
    proxy_pass http://backend:8041;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # backend webhook
  location /webhook/ {
    proxy_pass http://backend:8041;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  #assets
  location /assets/img/tof/ {
    alias /data/scan2dine/assets/img/tof/;
    expires 30d;
    access_log off;
  }
}
